//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormativSubTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NormativSubTypes()
        {
            this.Results = new HashSet<Results>();
        }
    
        public int id { get; set; }
        public int id_NormativType { get; set; }
        public string SubTypeName { get; set; }
        public int id_gender { get; set; }
        public string Step { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual NormativTypes NormativTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Results> Results { get; set; }
    }
}
