//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Normativs
    {
        public int id { get; set; }
        public string SubTypeName { get; set; }
        public string Result { get; set; }
        public int id_Steps { get; set; }
        public int id_Medal { get; set; }
    
        public virtual Medal Medal { get; set; }
        public virtual Steps Steps { get; set; }
    }
}
