//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal_data()
        {
            this.Results = new HashSet<Results>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public string NameAdd { get { return Surname + " " + Name + " " + Patronymic; } }
        public System.DateTime Age { get; set; }
        public string Email { get; set; }
        public bool Med_certificate { get; set; }
        public string Passport_number { get; set; }
        public int id_step { get; set; }
        public string City { get; set; }
        public int id_gender { get; set; }
        public int id_medal { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Medal Medal { get; set; }
        public virtual Steps Steps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Results> Results { get; set; }
    }
}
