//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standarts
    {
        public int id { get; set; }
        public int id_step { get; set; }
        public int id_medal { get; set; }
        public decimal Shuttle_run { get; set; }
        public decimal Running { get; set; }
        public decimal Mixed_movement { get; set; }
        public decimal Pull_ups { get; set; }
        public decimal Pull_ups_light { get; set; }
        public decimal Push_ups { get; set; }
        public string Gymnastics { get; set; }
        public string Tourism { get; set; }
    }
}
